/*******************************************************
 *
 * THIS FILE IS AUTO-GENERATED, DO NOT EDIT THIS FILE!
 * To edit this file, edit the auto-coder located
 * in TLM/auto_code/py
 *
 ******************************************************/

#include <stdint.h>
#include "util/serialize.h"
#include "servers/FMGServer.h"

using namespace std;
using namespace AllStar::Core;
using namespace AllStar::Servers;

FMGServer * fmgServer = static_cast<FMGServer *> (Factory::GetInstance(FMG_SERVER_SINGLETON));

void TLM_STARTUP_ERROR(void) {
  size_t size = 3;
  uint8_t * buf = (uint8_t *) malloc(size);
  Serialize ser(buf, size);
  ser.serialize_uint16(0x0001);
  fmgServer->Log(DESTINATION_ERR, buf, size);
}

void TLM_SERVERS_CREATED(void) {
  size_t size = 3;
  uint8_t * buf = (uint8_t *) malloc(size);
  Serialize ser(buf, size);
  ser.serialize_uint16(0x0002);
  fmgServer->Log(DESTINATION_ERR, buf, size);
}

void TLM_MAIN_EXIT(void) {
  size_t size = 3;
  uint8_t * buf = (uint8_t *) malloc(size);
  Serialize ser(buf, size);
  ser.serialize_uint16(0x0003);
  fmgServer->Log(DESTINATION_ERR, buf, size);
}

void TLM_MODE_SWITCH(uint8 arg0) {
  size_t size = 4;
  uint8_t * buf = (uint8_t *) malloc(size);
  Serialize ser(buf, size);
  ser.serialize_uint16(0x0100);
  ser.serialize_uint8(arg0);
  fmgServer->Log(DESTINATION_MOD, buf, size);
}

void TLM_CREATING_ACPPACKET(int32 arg0) {
  size_t size = 7;
  uint8_t * buf = (uint8_t *) malloc(size);
  Serialize ser(buf, size);
  ser.serialize_uint16(0x0400);
  ser.serialize_int32(arg0);
  fmgServer->Log(DESTINATION_ACP, buf, size);
}

