/*******************************************************
 *
 * THIS FILE IS AUTO-GENERATED, DO NOT EDIT THIS FILE!
 * To edit this file, edit the auto-coder located
 * in TLM/auto_code/py
 *
 ******************************************************/

#include <stdint.h>
#include "util/serialize.h"

void TLM_STARTUP_ERROR(void);
void TLM_SERVERS_CREATED(void);
void TLM_BUS_LOAD_TEST(void);
void TLM_SPI_STATS(void);
void TLM_SAMPLE_TEST_2(void);
void TLM_SAMPLE_TEST_3(void);
void TLM_CREATING_ACPPACKET(int32 arg0);
