/*******************************************************
 *
 * THIS FILE IS AUTO-GENERATED, DO NOT EDIT THIS FILE!
 * To edit this file, edit the auto-coder located
 * in TLM/auto_code/py
 *
 ******************************************************/

namespace AllStar{
namespace Servers{

#include <stdint.h>
#include "util/serialize.h"
#include "servers/FMGServer.h"

void TLM_STARTUP_ERROR(void);
void TLM_SERVERS_CREATED(void);
void TLM_BUS_LOAD_TEST(void);
void TLM_SPI_STATS(void);
void TLM_SAMPLE_TEST_2(void);
void TLM_SAMPLE_TEST_3(void);
void TLM_CREATING_ACPPACKET(int32 arg0);
void TLM_CDH_HEALTH_AND_STATUS(int32 arg0, float arg1, float arg2, float arg3, float arg4);
}
}

