/*******************************************************
 *
 * THIS FILE IS AUTO-GENERATED, DO NOT EDIT THIS FILE!
 * To edit this file, edit the auto-coder located
 * in TLM/
 *
 ******************************************************/

#include "util/serialize.h"

namespace AllStar{
namespace Servers{

class CDHStatus : public Serialize {
public:
  Float cpu1; // 1  minute loads (% of CPU)
  Float cpu5; // 5  minute loads (% of CPU)
  Float cpu15; // 15 minute loads (% of CPU)
  Float memory; // % of memory
  void serialize(void);
  void deserialize(void);
};

class ACSStatus : public Serialize {
public:
  Uint32 MRP_X; 
  Uint32 MRP_Y; 
  Uint32 MRP_Z; 
  Uint32 ST_Status; 
  Uint32 RW_Speed_X; 
  Uint32 RW_Speed_Y; 
  Uint32 RW_Speed_Z; 
  void serialize(void);
  void deserialize(void);
};

class PLDStatus : public Serialize {
public:
  Uint8 powerFault; 
  Uint16 motorSpeed; 
  Uint8 thermistors[10]; 
  Uint8 acdDataWorking; 
  Uint16 control; 
  Uint8 byteSize; 
  void serialize(void);
  void deserialize(void);
};

class EPSStatus : public Serialize {
public:
  Uint16 current3v3; 
  Uint16 voltage3v3; 
  Uint16 currentVbat; 
  Uint16 voltageVbat; 
  Uint16 current12v; 
  Uint16 voltage12v; 
  Uint16 remainingCapacity; 
  Uint16 battCurrent; 
  Uint16 battVoltage; 
  Uint16 battStatus; 
  Uint16 frangCurrent; 
  Uint16 frangVoltage; 
  Uint16 convCurrentX; 
  Uint16 convThreshX; 
  Uint16 convCurrentY; 
  Uint16 convThreshY; 
  Uint16 convCurrentW; 
  Uint16 convThreshW; 
  void serialize(void);
  void deserialize(void);
};

}
}

