import time
import os

input_file = "dict.txt"

type_sizes = {
  "Int8"  : 1,
  "Int16" : 2,
  "Int32" : 4,
  "Int64" : 8,
  "UInt8" : 1,
  "UInt16": 2,
  "UInt32": 4,
  "UInt64": 8,
  "Float" : 4,
  "Double": 8,
  "Bool"  : 1
}


class auto_coder():

  def __init__(self, input_file):
    self.f = open(input_file)
    self.name = ""
    self.ID = ""
    self.dest = ""
    self.fmt_str = ""
    self.param_types = ""
    self.buf_size = 0
    self.type_list = []
    self.arg_list = []
    self.list_len = 0
    self.args = ""

  def __enter__(self):
    return self

  def __exit__(self, exc_type, exc_value, traceback):
    self.close_file()

  def close_file(self):
    self.f.close

  def header(self):
    print "/*******************************************************"
    print " *"
    print " * THIS FILE IS AUTO-GENERATED, DO NOT EDIT THIS FILE!"
    print " * To edit this file, edit the auto-coder located"
    print " * in TLM/auto-code.py"
    print " *"
    print " ******************************************************/"
    print

  def parse_data(self):
    self.name = self.f.readline().strip()
    self.ID = self.f.readline().strip()
    self.dest = self.f.readline().strip()
    self.fmt_str = self.f.readline().strip()
    self.param_types = self.f.readline().strip()
    self.f.readline()

  def eof(self):
    return True if not self.param_types else False

  def parse_params(self):
    if self.param_types != "None":
      self.type_list = self.param_types.split(",")
      self.list_len = len(self.type_list);
      for i in range(self.list_len):
        self.arg_list.append("arg" + str(i))

  def get_buf_size(self):
    self.buf_size = 2;
    for t in self.type_list:
      self.buf_size += type_sizes[t]

  def builf_args_string(self):
    for i in range(self.list_len):
      self.args += self.type_list[i].lower() + " " + self.arg_list[i] + ", "

    # Remove trailing comma and space
    self.args = self.args[0:-2]

  def print_func(self):
    print "void log_tlm_%s(%s) {" % (self.name, self.args)
    print "  uint8_t buf[%s];" % (self.buf_size)
    print "  ser.Serialize ser(buf, %s);" % (self.buf_size)
    print "  ser.serializeUInt16(%s);" % (self.ID)
    for i in range(self.list_len):
        print "  ser.serialize%s(%s);" % (self.type_list[i], self.arg_list[i])
    print "  fmgServer->Log(DESTINATION_%s, buf);" % (self.dest)
    print "}"
    print

  

with auto_coder(input_file) as coder:

  coder = auto_coder(input_file)
  coder.header()

  # Skip until begin tlm marker
  while coder.f.readline().strip() != "##### BEGIN TELEMETRY #####": pass

  while True:
    coder.parse_data()
    if coder.eof(): break
    coder.parse_params()
    coder.get_buf_size()
    coder.builf_args_string()
    coder.print_func()


