//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : AllStar
//  @ File Name : MessageHandler.cpp
//  @ Date : 2/9/2010
//  @ Author :
//
//


#include "core/MessageHandler.h"

namespace AllStar
{
    namespace Core
    {
        MessageHandler::MessageHandler(void )
        {

        }

        MessageHandler::MessageHandler(std::string nameIn)
        {

        }

        MessageHandler::MessageHandler(const MessageHandler & source)
        {

        }

        MessageHandler::~MessageHandler(void )
        {

        }

        MessageHandler & MessageHandler::operator=(const MessageHandler & source)
        {
        	return *this;
        }

        std::string MessageHandler::GetName() const
        {
        	return name;
        }

        void MessageHandler::SetName(std::string newName)
        {

        }

    }
}
