//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Phoenix
//  @ File Name : MessageHandlerRegistry.cpp
//  @ Date : 2/9/2010
//  @ Author : 
//
//


#include "core/MessageHandlerRegistry.h"
#include "core/ReturnMessage.h"
#include "core/ErrorMessage.h"
#include <cstdio>
#include <iostream>

//#include "boards/backplane/dbg_led.h"

using namespace Phoenix::Servers;

namespace Phoenix
{
    namespace Core
    {
        MessageHandlerRegistry::MessageHandlerRegistry(void )
        {

        }
        
        MessageHandlerRegistry::MessageHandlerRegistry(const MessageHandlerRegistry & source)
        {

        }
        
        MessageHandlerRegistry::~MessageHandlerRegistry(void )
        {
        
        }
        
        MessageHandlerRegistry & MessageHandlerRegistry::operator=(const MessageHandlerRegistry source)
        {
        	return *this;
        }
		
        bool MessageHandlerRegistry::RegisterHandler(const MessageIdentifierType & key, MessageHandler * handler)
        {
        	handlerMap.insert(make_pair(key, handler));
        	return true;
        }

        ReturnMessage * MessageHandlerRegistry::Invoke(const FSWPacket & packet)
        {
        	Message * msg = packet.GetMessagePtr();
        	std::map<MessageIdentifierType, MessageHandler*>::iterator it =
        			handlerMap.find(MessageIdentifierType(msg->GetType(), msg->GetOpcode()));

        	if (it == handlerMap.end() || it->second == NULL)
        	{
        		std::cout<<"\t MessageHandlerRegistry: Invoke(): Error, unrecognized opcode type"<<std::endl;
        		std::cout<<"\t MessageHandlerRegistry: Invoke(): Handler map end: "<<(it == handlerMap.end())<<std::endl;
        		std::cout<<"\t MessageHandlerRegistry: Invoke(): Handler map null: "<<(it->second == NULL)<<std::endl;
        		ErrorMessage error(ERROR_OPCODE_UNRECOGNIZED_TYPE);
        		return new ReturnMessage(&error, false);
        	}
        	else
        	{
        		std::cout<<"\t MessageHandlerRegistry: Invoke(): Handle called"<<std::endl;
        		return it->second->Handle(packet);
        	}
        }
        
    }
}
